watchers/blueprints/contact/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms_components import EmailField
from wtforms.validators import DataRequired, Length


class ContactForm(FlaskForm):
    email = EmailField("What's your e-mail address?",
                       [DataRequired(), Length(3, 254)])
    message = TextAreaField("What's your question or issue?",
                            [DataRequired(), Length(1, 8192)])

watchers/app.py
# from flask import Flask, render_template
#
# application = Flask(__name__)
#
#
# @application.route('/')
# def index():
#     return render_template("index.html")
#
# if __name__ == "__main__":
#     application.run(host="0.0.0.0", port=80)
#
#
#
# https://github.com/nickjj/build-a-saas-app-with-flask/blob/master
from flask import Flask
from celery import Celery
from werkzeug.debug import DebuggedApplication

from watchers.blueprints.page import page
from watchers.blueprints.contact import contact
from watchers.extensions import debug_toolbar, mail, csrf, flask_static_digest

CELERY_TASK_LIST = [
    'watchers.blueprints.contact.tasks',
]


def create_celery_app(app=None):
    """
    Create a new Celery object and tie together the Celery config to the app's
    config. Wrap all tasks in the context of the application.
    :param app: Flask app
    :return: Celery app
    """
    app = app or create_app()

    celery = Celery(app.import_name, broker=app.config['CELERY_BROKER_URL'],
                    include=CELERY_TASK_LIST)
    celery.conf["worker_send_task_events"] = True
    # from pprint import pprint
    # print("-" * 30)
    # pprint(celery.conf)
    # print("-" * 30)

    celery.conf.update(app.config)
    #celery.autodiscover_tasks(lambda: app.config["INSTALLED_APPS"])

    TaskBase = celery.Task

    class ContextTask(TaskBase):
        abstract = True

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)

    celery.Task = ContextTask
    return celery


def create_app(settings_override=None):
    """
    Create a Flask application using the app factory pattern.
    :param settings_override: Override settings
    :return: Flask app
    """
    app = Flask(__name__, static_folder='../public', static_url_path='')

    app.config.from_object('config.settings')

    if settings_override:
        app.config.update(settings_override)

    app.register_blueprint(page)
    app.register_blueprint(contact)
    extensions(app)

    if app.debug:
        app.wsgi_app = DebuggedApplication(app.wsgi_app, evalex=True)

    return app


def extensions(app):
    """
    Register 0 or more extensions (mutates the app passed in).
    :param app: Flask application instance
    :return: None
    """
    debug_toolbar.init_app(app)
    mail.init_app(app)
    csrf.init_app(app)
    flask_static_digest.init_app(app)

    return None

watchers/blueprints/contact/__init__.py
from watchers.blueprints.contact.views import contact

watchers/blueprints/contact/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    request,
    url_for,
    render_template)

from watchers.blueprints.contact.forms import ContactForm

contact = Blueprint('contact', __name__, template_folder='templates')


@contact.route('/contact', methods=['GET', 'POST'])
def index():
    form = ContactForm()

    if form.validate_on_submit():
        # This prevents circular imports.
        from watchers.blueprints.contact.tasks import deliver_contact_email

        deliver_contact_email.delay(request.form.get('email'),
                                    request.form.get('message'))

        flash('Thanks, expect a response shortly.', 'success')
        return redirect(url_for('contact.index'))

    return render_template('contact/index.html', form=form)

watchers/blueprints/page/__init__.py
from watchers.blueprints.page.views import page

watchers/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')


@page.route('/healthy')
def healthy():
    return ''

watchers/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
    </head>
    <body>
        <script src="{{ url_for('static', filename='js/index.js') }}"></script>
    </body>
</html>

watchers/templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ static_url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link
      rel="stylesheet"
      href="{{ static_url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ static_url_for('static', filename='styles/vendor/font-awesome.min.css') }}">
    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{{ url_for('page.home') }}">
            <img src="{{ static_url_for('static', filename='images/snake-eyes.jpg') }}"
                 class="img-responsive"
                 width="229" height="50" title="Watchers" alt="Watchers"/>
          </a>
        </div>
      </div>
    </nav>

    <main class="container">
      {{ flash.render() }}

      <div class="md-margin-top">{% block heading %}{% endblock %}</div>
      {% block body %}{% endblock %}
    </main>

    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">Watchers &copy; 2019</li>
          <li><a href="{{ url_for('contact.index') }}">Contact</a></li>
          <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
          <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
        </ul>
      </div>
    </footer>

    <script
      src="{{ static_url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
  </body>
</html>

watchers/templates/macros/flash.html
{# Render Flask messages. #}
{%- macro render() -%}
  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      <div id="flash-messages" class="row sm-margin-top">
        {% for category, msg in messages %}
          <div class="alert alert-{{ category }}" role="alert">
            {{ msg }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
{%- endmacro -%}

watchers/templates/macros/form.html
{# Render a form field's label with visual aid to see if it's required. #}
{%- macro field_label(f) -%}
  <label for="{{ f.id }}">
    {%- if f.flags.required -%}
      <strong>{{ f.label.text }}</strong>
    {%- else %}
      {{ f.label.text }}
    {%- endif %}
  </label>
{%- endmacro -%}


{# Render a form field's errors. #}
{%- macro field_errors(f) -%}
  {% if f.errors %}
    <ul class="list-unstyled text-danger field-error">
      {% for error in f.errors %}
          <li>{{ error | e }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{%- endmacro -%}


{# Render a form field. #}
{%- macro field(f, css_class='form-control') -%}
  {{ f(class=css_class, **kwargs) }}
{%- endmacro -%}


{# Render a checkbox field. #}
{%- macro checkbox_field(f) -%}
  {{ f(type='checkbox', **kwargs) }} {{ f.label }}
{%- endmacro -%}


{# Render a form group with errors for various field types. #}
{%- macro form_group(f, css_class='') -%}
  {% if f.errors %}
    {% set css_class = css_class + ' has-error ' + kwargs.pop('class', '') %}
  {% endif %}

  {% if f.type == 'BooleanField' %}
      <div class="checkbox {{ css_class }}">
    {{ checkbox_field(f, **kwargs) }}
  {% else %}
      <div class="form-group {{ css_class }}">
    {{ field_label(f) }}
    {{ field(f, **kwargs) }}
  {% endif %}

    {{ field_errors(f) }}
    {{ caller () }}
  </div>
{%- endmacro %}


{# Render a form tag that contains a CSRF token and all hidden fields. #}
{%- macro form_tag(endpoint, fid='', css_class='', method='post') -%}
  <form action="{{ url_for(endpoint, **kwargs) }}" method="{{ method }}"
        id="{{ fid }}" class="{{ css_class }}" role="form">
    {{ form.hidden_tag() }}
    {{ caller () }}
  </form>
{%- endmacro -%}